name: Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: mvn -B clean package -DskipTests
        working-directory: /home/runner/work/TEAM-1-PM-Dozentenverwaltung/TEAM-1-PM-Dozentenverwaltung/lecturer-assignment-system